# Generated by Django 5.2 on 2025-04-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bids_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='item_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='price',
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='auction',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
