# Generated by Django 5.2 on 2025-04-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_item_name_auction_title_remove_auction_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
