# Generated by Django 5.2 on 2025-04-26 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_is_active_auction_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
